# Generated by Django 4.0.4 on 2022-05-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('200 To 300', '200 To 300'), ('0 To 100', '0 To 100'), ('400 To 500', '400 To 500'), ('300 To 400', '300 To 400'), ('100 To 200', '100 To 200')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
