# Generated by Django 4.0.4 on 2022-05-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_price_price_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('300 To 400', '300 To 400'), ('200 To 300', '200 To 300'), ('100 To 200', '100 To 200'), ('0 To 100', '0 To 100'), ('400 To 500', '400 To 500')], max_length=100),
        ),
    ]
