# Generated by Django 4.0.4 on 2022-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('200 To 300', '200 To 300'), ('100 To 200', '100 To 200'), ('400 To 500', '400 To 500'), ('300 To 400', '300 To 400'), ('0 To 100', '0 To 100')], max_length=100),
        ),
    ]
