# Generated by Django 4.0.4 on 2022-05-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_filter', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'blank')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_filter', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'blank')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('100 To 200', '100 To 200'), ('400 To 500', '400 To 500'), ('0 To 100', '0 To 100'), ('200 To 300', '200 To 300'), ('300 To 400', '300 To 400')], max_length=100),
        ),
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Images/homeproduct')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homecategories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homesubcategories')),
            ],
        ),
    ]
