# Generated by Django 4.0.4 on 2022-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homecategories_homesubcategories_alter_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategories',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('blank', 'blank')], max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('300 To 400', '300 To 400'), ('200 To 300', '200 To 300'), ('100 To 200', '100 To 200'), ('0 To 100', '0 To 100'), ('400 To 500', '400 To 500')], max_length=100),
        ),
    ]
