# Generated by Django 4.0.4 on 2022-05-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homecategories_status_alter_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproduct',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('100 To 200', '100 To 200'), ('200 To 300', '200 To 300'), ('300 To 400', '300 To 400'), ('0 To 100', '0 To 100'), ('400 To 500', '400 To 500')], max_length=100),
        ),
        migrations.DeleteModel(
            name='HomeSubCategories',
        ),
    ]
